<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    '253c157292f75eb38082b5acb06f3f01' => $vendorDir . '/nikic/fast-route/src/functions.php',
    '2610a18e262a9328d59872ebc8f6b5db' => $vendorDir . '/fpdo/fluentpdo/FluentPDO/FluentPDO.php',
);
